# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///chivdb
    username: root
    password: 1234
    dbcp2:
      max-idle: 100
      min-idle: 10
    type: org.apache.commons.dbcp2.BasicDataSource
