# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///chivdb
    username: root
    password: 1234
    type: com.mchange.v2.c3p0.ComboPooledDataSource
c3p0:
  min-size: 10
  max-size: 100
